apps/cart/urls.py
from django.conf.urls import url,include
from cart.views import CartAddView,CartInfoView,CartUpdateView,CartDeleteView

urlpatterns = [
    url(r'^add$',CartAddView.as_view(),name='add'),
    url(r'^$',CartInfoView.as_view(),name='show'),
    url(r'^update$',CartUpdateView.as_view(),name='update'),
    url(r'^delete$',CartDeleteView.as_view(),name='delete'),
]

apps/goods/urls.py
from django.conf.urls import url,include
from goods.views import IndexView,DetailView,ListView

urlpatterns = [
    url(r'^index$', IndexView.as_view(), name='index'), # 首页
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'), # 商品详情
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$',ListView.as_view(),name='list'), # 列表页
]

apps/order/urls.py
from django.conf.urls import url,include
from order.views import OrderPlaceView, OrderCommitView,OrderPayView,CheckPayView,CommentView

urlpatterns = [
    url(r'^place$',OrderPlaceView.as_view(),name='place'), # 显示订单页面
    url(r'^commit$',OrderCommitView.as_view(),name='commit'), # 提交订单
    url(r'^pay$',OrderPayView.as_view(),name='pay'), # 订单支付
    url(r'^check$',CheckPayView.as_view(),name='check'), # 查询支付交易结果
    url(r'^comment/(?P<order_id>.+)$',CommentView.as_view(),name='comment'), # 订单评论
]

apps/user/urls.py
from django.conf.urls import url,include
from user.views import RegisterView, ActiveView, LoginView,LogoutView,UserInfoView,UserOrderView,AddressView

urlpatterns = [
    url(r'^register$',RegisterView.as_view(),name='register'),
    url(r'^active/(?P<token>.*)$',ActiveView.as_view(),name='active'),

    url(r'^login$',LoginView.as_view(),name='login'),
    url(r'^logout$',LogoutView.as_view(),name='logout'),

    url(r'^$',UserInfoView.as_view(),name='user'),
    url(r'^order/(?P<page>\d+)$',UserOrderView.as_view(),name='order'),
    url(r'^address$',AddressView.as_view(),name='address'),

]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'search/',include('haystack.urls')), # 全文检索框架
    url(r'^user/', include(('user.urls','user'), namespace='user')),  # 用户模块
    url(r'^cart/', include(('cart.urls','cart'), namespace='cart')),  # 购物车模块
    url(r'^order/', include(('order.urls','order'), namespace='order')),  # 订单模块
    url(r'^', include(('goods.urls','goods'), namespace='goods')),  # 商品模块
]

apps/cart/models.py
from django.db import models

apps/cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import View
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin

from goods.models import GoodsSKU

# Create your views here.

class CartAddView(View):
    '''
    向购物车中添加商品,就是对redis中的数据进行增删改查
    '''
    def post(self,request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0, 'errmsg':'请先登录'})

        # 获取前端传来的数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 验证前端穿过来的数据的完整性及合法性
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        try:
            count = int(count) # 检测商品数量是不是整数
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        try:
            sku = GoodsSKU.objects.get(id=sku_id) # 检测商品是不是存在
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':3, 'errmsg':'商品不存在'})

        # 将商品添加到用户的购物车中
        sr_conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        cart_count = sr_conn.hget(cart_key,sku_id)
        if not cart_count:
            count = count
        else:
            count += cart_count

        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
        sr_conn.hset(cart_key, sku_id, count)

        total_count = sr_conn.hlen(cart_key)

        return JsonResponse({'res':5,'total_count':total_count,'message':'添加成功'})


class CartInfoView(LoginRequiredMixin,View):
    '''
    显示购物车中的内容
    '''
    def get(self,request):
        '''
        从redis中获取用户购物车中{'商品id':'商品数量'}构成的字典
        :param request:
        :return:
        '''
        user = request.user
        sr_conn = get_redis_connection('default')
        cart_key = "cart_%d"%user.id
        cart_dict = sr_conn.hgetall(cart_key)

        skus = []
        total_count = 0
        total_price = 0
        for sku_id,count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            # 获取此种商品的购买的总数和总价格
            sku.amount = sku.price * int(count)
            sku.count = count
            skus.append(sku)

            total_count += int(count)
            total_price += sku.amount

        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus
        }

        return render(request,'cart.html',context)


class CartUpdateView(View):
    '''
    增加或减少某客户购物车中商品的数量
    '''
    def post(self,request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0, 'errmsg':'请先登录'})

        # 获取前端传来的数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 验证前端穿过来的数据的完整性及合法性
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        try:
            count = int(count) # 检测商品数量是不是整数
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        try:
            sku = GoodsSKU.objects.get(id=sku_id) # 检测商品是不是存在
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':3, 'errmsg':'商品不存在'})

        # 获取商品存货,如果存货小于购买量,返回错误信息
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        cart_key = "cart_%d"%user.id
        sr_conn = get_redis_connection('default')
        sr_conn.hset(cart_key, sku_id, count)

        # 计算商品总件数
        total_count = 0
        goods_count = sr_conn.hvals(cart_key)
        for val in goods_count:
            total_count += int(val)

        return JsonResponse({'res':5, 'total_count':total_count, 'message':'更新成功'})


class CartDeleteView(View):
    '''
    删除购物车中的商品
    '''
    def post(self,request):
        user = request.user
        if not user.is_authenticated(): # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 获取前端传来的数据
        sku_id = request.POST.get('sku_id')

        if (not sku_id) or (not sku_id.isdigit()): # 如果商品id是空或者不是数字
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id) # 检测商品是不是存在
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':2, 'errmsg':'商品不存在'})

        # 删除某用户购物车中的商品
        cart_key = "cart_%d"%user.id
        sr_conn = get_redis_connection('default')
        sr_conn.hdel(cart_key,sku_id)

        # 计算商品总件数
        total_count = 0
        goods_count = sr_conn.hvals(cart_key)
        for val in goods_count:
            total_count += int(val)

        return JsonResponse({'res':3, 'total_count':total_count, 'message':'删除成功'})

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %}{% endblock topfiles %}
</head>

<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con %}

{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网站主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{% extends 'base.html' %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页，列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_user_center.html
{% extends 'base_no_cart.html' %}

{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}

{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心右侧内容块 #}
        {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}

templates/cart.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}

{% block title %}天天生鲜-购物车{% endblock title %}

{% block page_title %}购物车{% endblock page_title %}

{% block body %}
    {% csrf_token %}
	<div class="total_count">全部商品<em>{{ total_count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

    <form method="post" action="{% url 'order:place' %}">
        {% for sku in skus %}
            <ul class="cart_list_td clearfix">
                <li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked></li>
                <li class="col02"><img src="{{ sku.image.url }}"></li>
                <li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
                <li class="col04">{{ sku.unite }}</li>
                <li class="col05">{{ sku.price }}元</li>
                <li class="col06">
                    <div class="num_add">
                        <a href="javascript:;" class="add fl">+</a>
                        <input type="text" class="num_show fl" value="{{ sku.count }}">
                        <a href="javascript:;" class="minus fl">-</a>
                    </div>
                </li>
                <li class="col07">{{ sku.amount }}元</li>
                <li class="col08"><a href="javascript:;">删除</a></li>
            </ul>
        {% endfor %}

        <ul class="settlements">
	    	<li class="col01"><input type="checkbox" name="" checked=""></li>
	    	<li class="col02">全选</li>
	    	<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
	    	<li class="col04"><input type="submit" value="去结算"></li>
	    </ul>
    </form>
{% endblock body %}

{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        //计算选中商品的总数和总价
        function update_page_info(){
            var total_count = 0;
            var total_price = 0;
            $('.cart_list_td').find(':checked').parents('ul').each(function () {
                var count = $(this).find('.num_show').val();
                var price = $(this).children('.col07').text();
                count = parseInt(count);
                price = parseFloat(price);
                total_count += count;
                total_price += price;
            });
            $('.settlements').find('em').text(total_price.toFixed(2));
            $('.settlements').find('b').text(total_count);
        }

        //计算单个商品的价格
        function update_goods_amount(sku_ul){
            var count = sku_ul.find('.num_show').val();
            var price = sku_ul.children('.col05').text();
            var amount = parseInt(count) * parseFloat(price);
            sku_ul.children('.col07').text(amount.toFixed(2)+'元');
        }

        //控制商品的全选，全不选按钮
        $('.settlements').find(':checkbox').change(function () {
            var is_checked = $(this).prop('checked');
            $('.cart_list_td').find(':checkbox').each(function () {
                $(this).prop('checked',is_checked);
            });
            update_page_info();
        });

        //单个商品的选中和不选中对全选的影响
        $('.cart_list_td').find(':checkbox').change(function () {
            var all_len = $('.cart_list_td').length;
            var checked_len = $('.cart_list_td').find(':checked').length;
            var is_all_checked = true;
            if (all_len > checked_len){
                is_all_checked = false;
            }
            $('.settlements').find(':checkbox').prop('checked',is_all_checked);
            update_page_info();
        });

        //向服务器端发送请求，更新购物车中的数据
        var error_update = false;
        var total = 0;
        function update_remote_cart_info(sku_id, count) {
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf};
            // 同步发送ajax请求
            $.ajaxSettings.async = false;
            $.post('/cart/update',params,function (data) {
                if(data.res == 5){
                    error_update = false;
                    total = data.total_count;
                }else {
                    error_update = true;
                    alert(data.errmsg);
                }
            });
            $.ajaxSettings.async = true;
        }

        //点击＋，增加一个购物车中的商品
        $('.add').click(function () {
            var sku_id = $(this).next().attr('sku_id');
            var count = $(this).next().val();

            count = parseInt(count) + 1;
            update_remote_cart_info(sku_id,count);

            if(error_update==false){
                $(this).next.val(count);
                update_goods_amount($(this).parents('ul'));
                var is_checked = $(this).parents('ul').find(':checkbox').prop('checked');
                if (is_checked){
                    update_page_info();
                }
                $('.total_count').children('em').text(total);
            }
        });

        //点击－，减少一个购物车中的商品
        $('.minus').click(function () {
            var sku_id = $(this).prev().attr('sku_id');
            var count = $(this).prev().val();
            count = parseInt(count)-1;
            if (count <= 0){
                return;
            }
            update_remote_cart_info(sku_id,count);
            if(error_update==false){
                $(this).prev.val(count);
                update_goods_amount($(this).parents('ul'));
                var is_checked = $(this).parents('ul').find(':checkbox').prop('checked');
                if (is_checked){
                    update_page_info();
                }
                $('.total_count').children('em').text(total);
            }
        });

        //自己在输入框中输入要购买的商品数量

        // 记录用户输入之前商品的数量
        var pre_count = 0;
        $('.num_show').focus(function () {
            pre_count = $(this).val();
        });

        $('.num_show').blur(function () {
            var sku_id = $(this).prev().attr('sku_id');
            var count = $(this).prev().val();

            if (isNaN(count) || count.trim().length==0 || parseInt(count)<=1){
                count = pre_count;
                return;
            }else {
                count = parseInt(count);
            }
            update_remote_cart_info(sku_id,count);
            if(error_update==false){
                $(this).val(count);
                update_goods_amount($(this).parents('ul'));
                var is_checked = $(this).parents('ul').find(':checkbox').prop('checked');
                if (is_checked){
                    update_page_info();
                }
                $('.total_count').children('em').text(total);
            }else {
                // 更新失败
                $(this).val(pre_count);
            }
        });
        
        // 删除某个商品
        $('.cart_list_td').children('.col08').children('a').click(function () {
            var sku_id = $(this).parents('ul').find('.num_show').attr('sku_id');
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            var params = {'sku_id':sku_id, 'csrfmiddlewaretoken':csrf};
            var sku_ul = $(this).parents('ul');
            $.post('/cart/delete',params,function (data) {
                if(data.res==3){
                    sku_ul.remove();
                    var is_checked = sku_ul.find(':checkbox').prop('checked');
                    if (is_checked){
                        update_page_info();
                    }
                    $('.total_count').children('em').text(data.total_count);
                }else {
                    alert(data.errmsg);
                }
            });
        });

    </script>
{% endblock bottomfiles %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners  %}
				    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-商品列表{% endblock title %}

{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price}}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

            <!-- 分页显示 -->
			<div class="pagenation">
                {% if skus_page.has_previous %}
				<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}"><上一页</a>
                {% endif %}

                {% for pindex in page_range %}
                    {% if pindex == skus_page.number %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
				{% endfor %}

                {% if skus_page.has_next %}
				<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}

templates/static_index.html
{% extends 'static_base.html' %}
{% load staticfiles %}

{% block title %}天天生鲜-首页{% endblock title %}

{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners  %}
				    <li><a href="#"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'goods:detail' banner.sku.id %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}